# Generated by Django 4.1.5 on 2023-03-17 23:09

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('wagtailimages', '0024_index_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name_plural': 'recipe categories',
            },
        ),
        migrations.CreateModel(
            name='RecipePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('recipe_title', models.CharField(max_length=255)),
                ('recipe_title_text', models.CharField(blank=True, max_length=150)),
                ('recipe_content', wagtail.fields.StreamField([('content', wagtail.blocks.StructBlock([('ingredients', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('ingredient', wagtail.blocks.CharBlock(max_length=255)), ('handy_measure', wagtail.blocks.CharBlock(max_length=255, required=False)), ('metric', wagtail.blocks.CharBlock(max_length=20, required=False))]))), ('body', wagtail.blocks.RichTextBlock())]))], use_json_field=True)),
                ('date', models.DateField(auto_now=True, verbose_name='Post Date')),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='recipe.recipecategory')),
                ('recipe_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='RecipeIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
